{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DIM_Product\",\"DIM_Manufacturer\",\"DIM_Geography\",\"DIM_Distributor\",\"FACT_Production\",\"FACT_Sales\",\"Production_helper\",\"Regions_helper\",\"_Measures\",\"DataFileDirectory\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Production_helper",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
          "    Table24_Table = Source{[Item=\"Table24\",Kind=\"Table\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Table24_Table,{{\"Date\", type date}, {\"Product Group;Product ID\", type text}, {\"ManufacturerID\", Int64.Type}, {\"ManufacturerName\", type text}, {\"Country\", type text}, {\"Address\", type text}, {\"FactoryRating\", Int64.Type}, {\"Hiring\", Int64.Type}, {\"SpeedRating\", Int64.Type}, {\"FactoryType\", type text}, {\"Cost\", type number}, {\"Quantity\", type number}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"Product Group;Product ID\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"Product Group2\", \"Product ID\"}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Split Column by Delimiter\",{\"Product Group2\", \"Product ID\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "68c62171-851c-4819-b7fd-eedb1eaf8d15",
        "queryGroup": "Helper"
      },
      {
        "name": "Regions_helper",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
          "    Table2_Table = Source{[Item=\"Table2\",Kind=\"Table\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Table2_Table,{{\"Date\", type date}, {\"Product Group\", type text}, {\"Product ID\", type text}, {\"Region\", type text}, {\"Country\", type text}, {\"ManufacturerID\", Int64.Type}, {\"Distributor\", type text}, {\"Revenue\", type number}, {\"Cost\", type number}, {\"Quantity\", type number}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Region\", \"Country\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "246e5e26-bb77-4789-a52d-913fc443977a",
        "queryGroup": "Helper"
      },
      {
        "name": "DataFileDirectory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"C:\\Users\\sinta\\Documents\\PowerBI Kurs\\CS3\\Tkaninexpol_CaseStudy_3+(1).xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "6c119bd3-c96b-41a1-808a-fa9dfeb7b8c0",
        "queryGroup": "Parameters"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "DIM"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "FACT"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Helper"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Parameters"
      }
    ],
    "relationships": [
      {
        "name": "7e91615d-b5bf-4e54-b33b-ce843dbde9c1",
        "fromColumn": "Date",
        "fromTable": "FACT_Production",
        "toColumn": "Date",
        "toTable": "DIM_Date"
      },
      {
        "name": "f895c78b-ecca-4c91-93f5-5037c34c1477",
        "fromColumn": "Date",
        "fromTable": "FACT_Sales",
        "toColumn": "Date",
        "toTable": "DIM_Date"
      },
      {
        "name": "61cfea87-09f5-42b2-9d6b-525f3a8de953",
        "fromColumn": "ManufacturerID",
        "fromTable": "FACT_Production",
        "toColumn": "ManufacturerID",
        "toTable": "DIM_Manufacturer"
      },
      {
        "name": "67e29a15-c2d1-4a3a-bd22-2dd5f8f1f9fc",
        "fromColumn": "ManufacturerID",
        "fromTable": "FACT_Sales",
        "toColumn": "ManufacturerID",
        "toTable": "DIM_Manufacturer"
      },
      {
        "name": "cf1f5895-9ff5-468c-aebe-8219c7070af9",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "ManufacturerID",
        "fromTable": "DIM_Geography",
        "toColumn": "ManufacturerID",
        "toTable": "DIM_Manufacturer"
      },
      {
        "name": "c23fd8ff-5c59-4a81-b0a2-d2252a9aefae",
        "fromColumn": "DistributorID",
        "fromTable": "FACT_Sales",
        "toColumn": "Index",
        "toTable": "DIM_Distributor"
      },
      {
        "name": "5672a88b-a5c7-437c-b8a3-c94791ea931d",
        "fromColumn": "ProductKey",
        "fromTable": "FACT_Production",
        "toColumn": "Index",
        "toTable": "DIM_Product"
      },
      {
        "name": "78f8635a-6e02-47a9-9634-f2fa6256765a",
        "fromColumn": "ProductKey",
        "fromTable": "FACT_Sales",
        "toColumn": "Index",
        "toTable": "DIM_Product"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DIM_Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Product Group2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95379225-11bb-46ff-97dc-d45e09aa5305",
            "sourceColumn": "Product Group2",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "671cbc65-5883-47fb-82df-ffd54d05d6b1",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "15bd7b40-a671-4f0f-8107-42de3518585c",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7cbbf57f-8967-499a-b6aa-2b376ad9ad83",
        "partitions": [
          {
            "name": "DIM_Product",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"ProductKey\", Int64.Type}, {\"Product Group2\", type text}, {\"Product ID\", type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Product Group2\", \"Product ID\"}),",
                "    #\"Appended Query\" = Table.Combine({#\"Removed Other Columns\", Production_helper}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Appended Query\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FACT_Production",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "c9867644-cc71-4863-a337-25f961edb726",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "ManufacturerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3e7f776b-60f2-40b2-b7b5-acc64e847e17",
            "sourceColumn": "ManufacturerID",
            "summarizeBy": "none"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73f0cebd-c783-4819-b99b-220eef6f0f6a",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f4647298-03c9-453c-9892-bf990dcda03b",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "IsHiring",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e7e05fa6-cdc4-46c4-a7fc-63a24a75c9f5",
            "sourceColumn": "IsHiring",
            "summarizeBy": "none"
          },
          {
            "name": "SpeedRatingMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "692e6654-5097-478c-b206-18c7ac7264ee",
            "sourceColumn": "SpeedRatingMode",
            "summarizeBy": "none"
          },
          {
            "name": "Unit_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a7ffdd4-6235-4cd5-8b7a-f6c2e4786bc1",
            "sourceColumn": "Unit_Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "GeoID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "518ac502-3ad8-438d-9b8a-a8912947337e",
            "sourceColumn": "GeoID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bd9c8bff-bbfd-4f68-872b-a03762f926f5",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3d54fafb-ebaa-4023-ab3a-bc79a6405aab",
        "partitions": [
          {
            "name": "FACT_Production",
            "mode": "import",
            "queryGroup": "FACT",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
                "    Table24_Table = Source{[Item=\"Table24\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table24_Table,{{\"Date\", type date}, {\"Product Group;Product ID\", type text}, {\"ManufacturerID\", Int64.Type}, {\"ManufacturerName\", type text}, {\"Country\", type text}, {\"Address\", type text}, {\"FactoryRating\", Int64.Type}, {\"Hiring\", Int64.Type}, {\"SpeedRating\", Int64.Type}, {\"FactoryType\", type text}, {\"Cost\", type number}, {\"Quantity\", type number}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"Product Group;Product ID\", Splitter.SplitTextByDelimiter(\";\", QuoteStyle.Csv), {\"Product Group 2\", \"Product Id\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Split Column by Delimiter\", \"IsHiring\", each if [Hiring] = 1 then \"Yes\" else if [Hiring] = 0 then \"No\" else \"N/A\"),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"SpeedRatingMode\", each if [SpeedRating] = 3 then \"Fast\" else if [SpeedRating] = 2 then \"Normal\" else if [SpeedRating] = 1 then \"Slow\" else \"N/A\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"IsHiring\", type text}, {\"SpeedRatingMode\", type text}}),",
                "    #\"Inserted Division\" = Table.AddColumn(#\"Changed Type1\", \"Unit_Cost\", each if [Quantity] = 0 then 0 else [Cost] / [Quantity], type number),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Inserted Division\", {\"Product Group 2\", \"Product Id\"}, DIM_Product, {\"Product Group2\", \"Product ID\"}, \"DIM_Product\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_Product\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DIM_Product\", {\"Index\"}, {\"ProductKey\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Expanded DIM_Product\",{\"Date\", \"ManufacturerID\", \"Cost\", \"Quantity\", \"IsHiring\", \"SpeedRatingMode\", \"Unit_Cost\", \"ProductKey\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Removed Other Columns\", {\"ManufacturerID\"}, DIM_Manufacturer, {\"ManufacturerID\"}, \"Manufacturer_helper\", JoinKind.LeftOuter),",
                "    #\"Expanded Manufacturer_helper\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Manufacturer_helper\", {\"ManufacturerName\"}, {\"ManufacturerName\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Expanded Manufacturer_helper\", {\"ManufacturerID\"}, DIM_Geography, {\"ManufacturerID\"}, \"DIM_Geography\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_Geography\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"DIM_Geography\", {\"GeoID\"}, {\"GeoID\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Expanded DIM_Geography\",{\"Date\", \"ManufacturerID\", \"Cost\", \"Quantity\", \"IsHiring\", \"SpeedRatingMode\", \"Unit_Cost\", \"ProductKey\", \"GeoID\"})",
                "in",
                "    #\"Removed Other Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FACT_Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "4b409467-dea7-48fd-a913-5dec836e7b12",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "ManufacturerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dfdd9341-4301-44cb-beb6-d2b7fa7f98a4",
            "sourceColumn": "ManufacturerID",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5ab7c2a4-7dad-459f-8483-4fd258e48843",
            "sourceColumn": "Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a28c3a4b-2a6d-4993-98d7-7d4b5fa6c415",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c84b36a9-849c-42dc-8643-9a8d48075cd8",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5dbe0938-794f-45bf-801d-416cb047679d",
            "sourceColumn": "Unit_Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "GeoID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c907e31b-bee0-4062-8295-6f335b812a6a",
            "sourceColumn": "GeoID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7c45cd66-207e-4f6c-ba5c-e1b07e689e43",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "DistributorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2134854a-23e9-4003-a372-3898ee48120d",
            "sourceColumn": "DistributorID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d71ac170-e393-4bf6-82a7-9cac1c7f7268",
        "partitions": [
          {
            "name": "FACT_Sales",
            "mode": "import",
            "queryGroup": "FACT",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
                "    Table2_Table = Source{[Item=\"Table2\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table2_Table,{{\"Date\", type date}, {\"Product Group\", type text}, {\"Product ID\", type text}, {\"Region\", type text}, {\"Country\", type text}, {\"ManufacturerID\", Int64.Type}, {\"Distributor\", type text}, {\"Revenue\", type number}, {\"Cost\", type number}, {\"Quantity\", type number}}),",
                "    #\"Inserted Division\" = Table.AddColumn(#\"Changed Type\", \"Unit_Cost\", each if [Quantity] = 0 then 0 else [Cost] / [Quantity], type number),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Inserted Division\", {\"Product Group\", \"Product ID\"}, DIM_Product, {\"Product Group2\", \"Product ID\"}, \"DIM_Product\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_Product\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DIM_Product\", {\"Index\"}, {\"ProductKey\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Expanded DIM_Product\",{\"Date\", \"ManufacturerID\", \"Distributor\", \"Revenue\", \"Cost\", \"Quantity\", \"Unit_Cost\", \"ProductKey\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Removed Other Columns\", {\"ManufacturerID\"}, DIM_Geography, {\"ManufacturerID\"}, \"DIM_Geography\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_Geography1\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"DIM_Geography\", {\"GeoID\"}, {\"GeoID\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Expanded DIM_Geography1\", {\"Distributor\"}, DIM_Distributor, {\"DistributorName\"}, \"DIM_Distributor\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_Distributor\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"DIM_Distributor\", {\"Index\"}, {\"Index\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded DIM_Distributor\",{{\"Index\", \"DistributorID\"}}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns\",{\"Date\", \"ManufacturerID\", \"Revenue\", \"Cost\", \"Quantity\", \"Unit_Cost\", \"ProductKey\", \"GeoID\", \"DistributorID\"})",
                "in",
                "    #\"Removed Other Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "33de174260984b8c8a4670a3b67a5517"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "2a65a5aa-fc1b-44ff-a8d6-04ae68ab983f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c4d31433-ec5e-4f29-99b2-a978fb830297",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "017e2fac-c956-47b8-8b5b-9b13f67e69ae",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7ad5081e-958d-4825-9c81-5c3b32524a85",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b314ea30-0f19-4f5e-aa04-b1be89f1f848",
            "sortByColumn": "Month",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4885707a-28e2-4857-b9ea-ca73e3e1f28e",
            "sourceColumn": "[Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "50e84a6e-fe7e-41e1-8dd8-d015edf659fd",
            "sortByColumn": "Week",
            "sourceColumn": "[Week Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9f3c7131-bf54-48c5-8f72-62ba9711a1d9",
            "sourceColumn": "[Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "caecf34d-a627-418a-87c2-8fbb50f45b12",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "02d6296a-805e-45fd-b773-b6891f493cb3",
                "ordinal": 1
              },
              {
                "name": "Month Name",
                "column": "Month Name",
                "lineageTag": "003cad3e-3306-41d2-8f42-99df032a308c",
                "ordinal": 2
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7712878c-a8cb-49a0-8b65-522eddb75e7c",
                "ordinal": 3
              },
              {
                "name": "Week Name",
                "column": "Week Name",
                "lineageTag": "c8f795b5-4ff7-46c7-ab5d-c33f02787e26",
                "ordinal": 4
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "66f92939-8ce9-4b65-8934-30bc8278fb26",
                "ordinal": 5
              }
            ],
            "lineageTag": "e9ca33f1-8e9f-4313-9098-a929b87d6e1a"
          }
        ],
        "lineageTag": "14d73285-d1a7-4972-be57-0a9c903b302f",
        "partitions": [
          {
            "name": "DIM_Date",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    CALENDARAUTO(12),",
                "    \"Year\", YEAR([Date]),",
                "    \"Quarter\", FORMAT([Date],\"\\QQ\"),",
                "    \"Month\", MONTH([Date]),",
                "    \"Month Name\", FORMAT([Date], \"mmm\"),",
                "    \"Week\", WEEKNUM([Date]),",
                "    \"Week Name\", CONCATENATE(\"Wk\", FORMAT(WEEKNUM([Date]), \"00\")),",
                "    \"Day\", DAY([Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DIM_Manufacturer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "ManufacturerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a186e79d-bd34-4db6-a738-b00a5b1cd959",
            "sourceColumn": "ManufacturerID",
            "summarizeBy": "none"
          },
          {
            "name": "ManufacturerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e24ae989-f9f1-4967-8bb8-b6d8460cb842",
            "sourceColumn": "ManufacturerName",
            "summarizeBy": "none"
          },
          {
            "name": "FactoryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8521ed1f-1726-454f-ad6a-ba9687322fbd",
            "sourceColumn": "FactoryType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "73f3afff-dc0e-4144-915b-811c8dd3ae67",
        "partitions": [
          {
            "name": "DIM_Manufacturer",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
                "    Table24_Table = Source{[Item=\"Table24\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table24_Table,{{\"Date\", type date}, {\"Product Group;Product ID\", type text}, {\"ManufacturerID\", Int64.Type}, {\"ManufacturerName\", type text}, {\"Country\", type text}, {\"Address\", type text}, {\"FactoryRating\", Int64.Type}, {\"Hiring\", Int64.Type}, {\"SpeedRating\", Int64.Type}, {\"FactoryType\", type text}, {\"Cost\", type number}, {\"Quantity\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"ManufacturerID\", \"ManufacturerName\", \"FactoryType\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_Geography",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ManufacturerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b1bd3e21-4b1b-4a66-872a-359bba993781",
            "sourceColumn": "ManufacturerID",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9d80923-2b6e-4e8a-8c06-56c6f87a1649",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c6536f4-40a9-4c2d-a1ee-896833004189",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96b6dab8-412e-4ae0-a67c-fcf7e69f97da",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "GeoID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca8b7a32-52de-4442-bbd7-93c78545f77b",
            "sourceColumn": "GeoID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4fb44da4-de95-4929-a8a0-2e2b777de458",
        "partitions": [
          {
            "name": "DIM_Geography",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
                "    Table24_Table = Source{[Item=\"Table24\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table24_Table,{{\"Date\", type date}, {\"Product Group;Product ID\", type text}, {\"ManufacturerID\", Int64.Type}, {\"ManufacturerName\", type text}, {\"Country\", type text}, {\"Address\", type text}, {\"FactoryRating\", Int64.Type}, {\"Hiring\", Int64.Type}, {\"SpeedRating\", Int64.Type}, {\"FactoryType\", type text}, {\"Cost\", type number}, {\"Quantity\", type number}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Country\"}, Regions_helper, {\"Country\"}, \"DIM_Regions\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_Regions\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DIM_Regions\", {\"Region\"}, {\"Region\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Expanded DIM_Regions\",{\"ManufacturerID\", \"Country\", \"Address\", \"Region\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"GeoID\", 1, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "a1458ac0-e993-4b7c-954e-f5ba56fe4857",
        "measures": [
          {
            "name": "Cost Per Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Cost",
            "expression": [
              "",
              "DIVIDE ( SUM ( FACT_Sales[Cost] ), SUM ( FACT_Sales[Quantity] ) )"
            ],
            "lineageTag": "3cc45ea8-1de6-4370-8abc-b79db1358516"
          },
          {
            "name": "Profit Per Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Profit",
            "expression": [
              "",
              "DIVIDE ( [Profit], SUM ( FACT_Sales[Quantity] ) )"
            ],
            "lineageTag": "2866e197-3a48-485f-b6bf-a8077dc641cf"
          },
          {
            "name": "Revenue Per Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Revenue",
            "expression": [
              "",
              "DIVIDE ( [Revenue], SUM ( FACT_Sales[Quantity] ) )"
            ],
            "lineageTag": "60baede6-909c-4b85-97f6-153b943c3236"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Revenue",
            "expression": [
              "",
              "VAR __PREV_MONTH =",
              "    CALCULATE ( [Revenue], ENDOFMONTH ( DATEADD ( 'DIM_Date'[Date], -1, MONTH ) ) )",
              "RETURN",
              "    IF ( ISBLANK ( [Revenue] ), __PREV_MONTH, [Revenue] )"
            ],
            "lineageTag": "ddaecdac-06e5-426e-ab3a-7b4fcd57e3a9"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Profit",
            "expression": [
              "",
              "SUMX ( FACT_Sales, FACT_Sales[Revenue] - FACT_Sales[Cost] )"
            ],
            "lineageTag": "00689c15-3a3b-485c-8252-4e2bae28495f"
          },
          {
            "name": "Latest Revenue MoM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Sales\\Revenue",
            "expression": [
              "",
              "IF (",
              "    MAX ( DIM_Date[Date] ) < ENDOFMONTH ( DIM_Date[Date] ),",
              "    CALCULATE (",
              "        [Total Revenue Prev Month],",
              "        ENDOFMONTH ( DATEADD ( DIM_Date[Date], -1, MONTH ) )",
              "    ),",
              "    CALCULATE ( [Total Revenue Prev Month], ENDOFMONTH ( DIM_Date[Date] ) )",
              ")"
            ],
            "formatString": "  +#.##;-#.##;0",
            "lineageTag": "8804a9fe-ba6d-4002-b7f6-4526fc66d431"
          },
          {
            "name": "Total Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Cost",
            "expression": [
              "",
              "VAR __PREV_MONTH =",
              "    CALCULATE ( [Cost], ENDOFMONTH ( DATEADD ( 'DIM_Date'[Date], -1, MONTH ) ) )",
              "RETURN",
              "    IF ( ISBLANK ( [Cost] ), __PREV_MONTH, [Cost] )"
            ],
            "lineageTag": "be3faabe-374a-4bbb-bbfb-751e9de4efe1"
          },
          {
            "name": "Latest Cost MoM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Sales\\Cost",
            "expression": [
              "",
              "IF (",
              "    MAX ( DIM_Date[Date] ) < ENDOFMONTH ( DIM_Date[Date] ),",
              "    CALCULATE (",
              "        [Total Cost Prev Month],",
              "        ENDOFMONTH ( DATEADD ( DIM_Date[Date], -1, MONTH ) )",
              "    ),",
              "    CALCULATE ( [Total Cost Prev Month], ENDOFMONTH ( DIM_Date[Date] ) )",
              ")"
            ],
            "formatString": "  +#.##;-#.##;0",
            "lineageTag": "c0406620-ca7d-47f2-a75a-fb6fcfbd5c2f"
          },
          {
            "name": "Latest Profit MoM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Sales\\Profit",
            "expression": [
              "",
              "IF (",
              "    MAX ( DIM_Date[Date] ) < ENDOFMONTH ( DIM_Date[Date] ),",
              "    CALCULATE (",
              "        [Total Profit Prev Month],",
              "        ENDOFMONTH ( DATEADD ( DIM_Date[Date], -1, MONTH ) )",
              "    ),",
              "    CALCULATE ( [Total Profit Prev Month], ENDOFMONTH ( DIM_Date[Date] ) )",
              ")"
            ],
            "formatString": " +#.##;-#.##;0",
            "lineageTag": "ca400628-cd46-4dfb-a408-4ee8ca0303ab"
          },
          {
            "name": "Map Tooltip Title",
            "displayFolder": "Other",
            "expression": [
              "",
              "CONCATENATE (",
              "    CONCATENATEX (",
              "        RELATEDTABLE ( DIM_Manufacturer ),",
              "        DIM_Manufacturer[ManufacturerName]",
              "    ),",
              "    \" - Total Revenue\"",
              ")"
            ],
            "lineageTag": "4929084f-f2c5-4dea-9aaf-f410902863f7"
          },
          {
            "name": "Latest Profit MoM Label",
            "displayFolder": "Sales\\Profit",
            "expression": [
              "",
              "VAR __START_DATE =",
              "    IF (",
              "        MAX ( DIM_Date[Date] ) = ENDOFMONTH ( DIM_Date[Date] ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -1, MONTH ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -2, MONTH )",
              "    )",
              "VAR __END_DATE =",
              "    IF (",
              "        MAX ( DIM_Date[Date] ) = ENDOFMONTH ( DIM_Date[Date] ),",
              "        MAX ( DIM_Date[Date] ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -1, MONTH )",
              "    )",
              "RETURN",
              "    \"Latest Profit\" & UNICHAR ( 10 ) & \"(\"",
              "        & FORMAT ( __END_DATE, \"mmm\", \"en-US\" ) & \"'\"",
              "        & FORMAT ( __END_DATE, \"yy\", \"en-US\" ) & \" vs. \"",
              "        & FORMAT ( __START_DATE, \"mmm\", \"en-US\" ) & \"'\"",
              "        & FORMAT ( __START_DATE, \"yy\", \"en-US\" ) & \")\""
            ],
            "lineageTag": "c79116fc-918b-47da-af63-47e726598741"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Profit",
            "expression": [
              "",
              "VAR __PREV_MONTH =",
              "    CALCULATE ( [Profit], ENDOFMONTH ( DATEADD ( 'DIM_Date'[Date], -1, MONTH ) ) )",
              "RETURN",
              "    IF ( ISBLANK ( [Profit] ), __PREV_MONTH, [Profit] )"
            ],
            "lineageTag": "0924b747-45f7-4b4e-af50-8e411cba90eb"
          },
          {
            "name": "Total Profit Prev Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Profit",
            "expression": [
              "",
              "VAR __PREV_MONTH =",
              "    CALCULATE (",
              "        [Total Profit],",
              "        ENDOFMONTH ( DATEADD ( DIM_Date[Date], -1, MONTH ) )",
              "    )",
              "VAR __PREV_2_MONTHS =",
              "    CALCULATE (",
              "        [Total Profit],",
              "        ENDOFMONTH ( DATEADD ( DIM_Date[Date], -2, MONTH ) )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( [Profit] ),",
              "        __PREV_MONTH - __PREV_2_MONTHS,",
              "        [Total Profit] - __PREV_MONTH",
              "    )"
            ],
            "lineageTag": "fff33180-2ad9-42c0-b358-6fac920c4194"
          },
          {
            "name": "Total Revenue Prev Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Revenue",
            "expression": [
              "",
              "VAR __PREV_MONTH =",
              "    CALCULATE (",
              "        [Total Revenue],",
              "        ENDOFMONTH ( DATEADD ( DIM_Date[Date], -1, MONTH ) )",
              "    )",
              "VAR __PREV_2_MONTHS =",
              "    CALCULATE (",
              "        [Total Revenue],",
              "        ENDOFMONTH ( DATEADD ( DIM_Date[Date], -2, MONTH ) )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( [Revenue] ),",
              "        __PREV_MONTH - __PREV_2_MONTHS,",
              "        [Total Revenue] - __PREV_MONTH",
              "    )"
            ],
            "lineageTag": "57662801-5ef6-4281-a0c6-0f3bbfe2677e"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Revenue",
            "expression": [
              "",
              "SUM ( FACT_Sales[Revenue] )"
            ],
            "lineageTag": "66f9c226-7272-4821-80f6-63f6ebb0a96d"
          },
          {
            "name": "Latest Revenue MoM Label",
            "displayFolder": "Sales\\Revenue",
            "expression": [
              "",
              "VAR __START_DATE =",
              "    IF (",
              "        MAX ( DIM_Date[Date] ) = ENDOFMONTH ( DIM_Date[Date] ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -1, MONTH ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -2, MONTH )",
              "    )",
              "VAR __END_DATE =",
              "    IF (",
              "        MAX ( DIM_Date[Date] ) = ENDOFMONTH ( DIM_Date[Date] ),",
              "        MAX ( DIM_Date[Date] ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -1, MONTH )",
              "    )",
              "RETURN",
              "    \"Latest Revenue \" & --  UNICHAR(10) &",
              "    \"(\"",
              "        & FORMAT ( __END_DATE, \"mmm\", \"en-US\" ) & \"'\"",
              "        & FORMAT ( __END_DATE, \"yy\", \"en-US\" ) & \" vs. \"",
              "        & FORMAT ( __START_DATE, \"mmm\", \"en-US\" ) & \"'\"",
              "        & FORMAT ( __START_DATE, \"yy\", \"en-US\" ) & \")\""
            ],
            "lineageTag": "cedce6fa-7d07-4525-a4ad-c2d8ce89cd45"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Cost",
            "expression": [
              "",
              "SUM ( FACT_Sales[Cost] )"
            ],
            "lineageTag": "f4f8d488-8b19-4a56-a2e5-ece1e2719080"
          },
          {
            "name": "Total Cost Prev Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales\\Cost",
            "expression": [
              "",
              "VAR __PREV_MONTH =",
              "    CALCULATE ( [Total Cost], ENDOFMONTH ( DATEADD ( DIM_Date[Date], -1, MONTH ) ) )",
              "VAR __PREV_2_MONTHS =",
              "    CALCULATE ( [Total Cost], ENDOFMONTH ( DATEADD ( DIM_Date[Date], -2, MONTH ) ) )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( [Cost] ),",
              "        __PREV_MONTH - __PREV_2_MONTHS,",
              "        [Total Cost] - __PREV_MONTH",
              "    )"
            ],
            "lineageTag": "179d19c4-9124-4b35-a656-5295a1c54138"
          },
          {
            "name": "Latest Cost MoM Label",
            "displayFolder": "Sales\\Cost",
            "expression": [
              "",
              "VAR __START_DATE =",
              "    IF (",
              "        MAX ( DIM_Date[Date] ) = ENDOFMONTH ( DIM_Date[Date] ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -1, MONTH ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -2, MONTH )",
              "    )",
              "VAR __END_DATE =",
              "    IF (",
              "        MAX ( DIM_Date[Date] ) = ENDOFMONTH ( DIM_Date[Date] ),",
              "        MAX ( DIM_Date[Date] ),",
              "        DATEADD ( LASTDATE ( DIM_Date[Date] ), -1, MONTH )",
              "    )",
              "RETURN",
              "    \"Latest Cost \" & --  UNICHAR(10) &",
              "    \"(\"",
              "        & FORMAT ( __END_DATE, \"mmm\", \"en-US\" ) & \"'\"",
              "        & FORMAT ( __END_DATE, \"yy\", \"en-US\" ) & \" vs. \"",
              "        & FORMAT ( __START_DATE, \"mmm\", \"en-US\" ) & \"'\"",
              "        & FORMAT ( __START_DATE, \"yy\", \"en-US\" ) & \")\""
            ],
            "lineageTag": "94d46db9-4b89-49ab-8b94-97b2849e29d1"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_Distributor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DistributorName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b61179de-8b07-41d7-ad97-099ee130fb7a",
            "sourceColumn": "DistributorName",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad1fe77f-1804-4103-9a5a-1bbacb443eec",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4c4f929f-0822-4d04-8f52-d7b448287598",
        "partitions": [
          {
            "name": "DIM_Distributor",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(DataFileDirectory), null, true),",
                "    Table2_Table = Source{[Item=\"Table2\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table2_Table,{{\"Date\", type date}, {\"Product Group\", type text}, {\"Product ID\", type text}, {\"Region\", type text}, {\"Country\", type text}, {\"ManufacturerID\", Int64.Type}, {\"Distributor\", type text}, {\"Revenue\", type number}, {\"Cost\", type number}, {\"Quantity\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Distributor\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Distributor\", \"DistributorName\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}